name: Laravel Build and Push

on:
  push:
    branches:
      - main # ou la branche principale de votre choix

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.1' # Choisissez la version PHP que vous utilisez

      
      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      
      - name: Generate Assets (si nécessaire)
        run: npm install  # ou toute commande pour générer les assets

      
      
      name: Notification Discord sur le statut des actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Vos étapes de déploiement ou autres actions vont ici

      - name: Envoyer une notification Discord
        uses: sarisia/actions-status-discord@v1.12.0
        if: always()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK }}
          status: ${{job.status }}
          content: "Hey @everyone"
          title: "Déploiement"
          url: "https://github.com/Sangoule/det-uad-laravel.git"
          username: GitHub Actions

      
      - name: Push Build
        uses: s0/git-publish-subdir-action@develop
        env:
            REPO: self
            BRANCH: build # Nom de la branche où vous souhaitez pousser les assets
            FOLDER: public # Dossier où vos assets sont générés (pour Laravel, il s'agit généralement du dossier "public")
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MESSAGE: "Build: ({sha}) {msg}" # Message de commit pour le build